# Generated by Django 4.1.5 on 2023-01-21 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auht_type',
            field=models.CharField(choices=[('via_email', 'via_email'), ('via_phone', 'via_phone'), ('super_admin', 'super_admin')], default='super_admin', max_length=35),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamingiz 9 bilan boshlanib va 12 ta raqamdan iborat bolsin', regex='^9\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('femail', 'femail')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_roles',
            field=models.CharField(choices=[('ordinary_user', 'ordinary_user'), ('manager', 'manager'), ('super_admin', 'super_admin')], default='ordinary_user', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
